// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB72YcrwHJyDFWDAToa-yvcv6lUhC0cns',
    appId: '1:117237674663:android:2e16986ac160c9f603e182',
    messagingSenderId: '117237674663',
    projectId: 'share-achieve-app',
    storageBucket: 'share-achieve-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCagdkmDJJhzctpYc4bZGgUbj5YKtTA_NU',
    appId: '1:117237674663:ios:2527dc6f414de08903e182',
    messagingSenderId: '117237674663',
    projectId: 'share-achieve-app',
    storageBucket: 'share-achieve-app.appspot.com',
    androidClientId: '117237674663-s1hq5q9ekbujh44uocs22vtc6o5np551.apps.googleusercontent.com',
    iosClientId: '117237674663-m8lg7v5rik2thj9tsqrt6d8kfuk1l0mq.apps.googleusercontent.com',
    iosBundleId: 'com.example.shareAchieveApp',
  );
}
